### ISSUE TITLE
Update to Kafka 0.9.0.0

### ISSUE THREAD

**Issue by TomMD** [tylerholien/milena#16]
Any thoughts on the delta between Kafka 0.8 and 0.9?  I'm looking to use Kafka 0.9 + melena so if there isn't already progress we might send in a PR - any experience you already have on this path would be appreciated.

**Comment by tylerholien** [comment]
The library works as-is with 0.9, but doesn't take advantage of the new protocols introduced in 0.9 (in particular the new-style groups). If you're using it to consume it's similar to the low-level 0.8.* consumer. I am actively working on implementing the new group protocols, so keep an eye out for those! I'll try to push a branch soon, and comments and PRs are welcome.

Sorry that development is so slow. This is a free-time only project and that free time is pretty much just on the bus!

**Comment by tylerholien** [comment]
I'll also update the readme to clarify support.

**Comment by TomMD** [comment]
Great to hear, thanks @tylerholien for the information and library.
