### ISSUE TITLE
Kafka 0.9.0 support

### ISSUE THREAD

**Issue by AlexeyRaga** [tylerholien/milena#26]
Hi, is Kafka 0.9.0 support planned?
Looks like it introduced some features that would make life easier for writing consumers, such as the ability to subscribe to a topic and built-in balancing consumer functionality.

**Comment by tylerholien** [comment]
The library already works with 0.9. I just updated the readme to reflect that.

**Comment by ysangkok** [comment]
What about 0.10? :)
