### ISSUE TITLE
Release with new version bounds?

### ISSUE THREAD

**Issue by TomMD** [tylerholien/milena#32]
Could we get a point release?

**Comment by tylerholien** [comment]
Sorry, I've been meaning to get back to work on this, but at this point I think I'm kidding myself. We don't use Haskell at work, and my time away from work has been taken up by other things. If someone would like to take over the project I'd be happy to transfer ownership.

**Comment by adamflott** [comment]
@tylerholien I use Haskell and this package at work! I'd be interested in taking ownership given I've spent enough time learning from it (and thanks for that too! :). However, I have no experience with maintaining on Hackage. Although the documentation makes it seem rather straight forward.

**Comment by tylerholien** [comment]
@adamflott Oh no, I hope you didn't learn too much from my crappy code! Hackage is pretty easy. Sometimes the docs don't get linked so you have to upload them separately, but it's possible that's fixed by now.

**Comment by adamflott** [comment]
Just the opposite! Yes they fixed the doc building issue a few months ago. If you're ok with transferring my Hackage username is adamflott

**Comment by tylerholien** [comment]
You're added!

**Comment by tylerholien** [comment]
@adamflott

**Comment by tylerholien** [comment]
Whoops, didn't mean to hit the close button.

**Comment by tylerholien** [comment]
@adamflott I also added you to this repo. Feel free to keep using it as the main repo or update the readme to point to a clone or whatever you want!

**Comment by adamflott** [comment]
@tylerholien Awesome. Thanks! I'll start taking action on this soon.

**Comment by adamflott** [comment]
Version 0.5.0.2 uploaded to Hackage with bumped bounds.
