### ISSUE TITLE
Zookeeper integration

### ISSUE THREAD

**Issue by bitemyapp** [tylerholien/milena#7]
Well. I pinged the two Zookeeper client maintainers. They both said their respective clients worked.

https://hackage.haskell.org/package/hzk-1.0.0 - they aren't properly Cabalized 

https://github.com/motus/haskell-zookeeper-client

I really have no idea for sure if they work. This a bookmark for further investigation and seeing what we want to do about integration.

I'm still not sold on clients controlling their offsets, but there might be other reasons to need/want to talk to the ZK cluster.

**Comment by tylerholien** [comment]
I'm working on implementing the new 0.9-style groups and don't plan on working on the 0.8.*-style, so closing this.

**Comment by bitemyapp** [comment]
@tylerholien wfm. Thank you :)
